### ISSUE TITLE
Don't try to auto register records

### ISSUE THREAD

**Issue by martonx** [JonPSmith/NetCore.AutoRegisterDi#12]
Hi,

As records has this syntax: 

public record CardMessage(int CardId, string Upc, string Amount, string LocalTransactionTime, string LocalTransactionDate, string RetrievalReferenceNumber)

NetCore.AutoRegisterDi tries to resolve all of the record constructor parameters as DI dependencies.

Intended behavior:
AutoRegisterDI should skip all of the records in the registering process.

**Comment by martonx** [comment]
Hi @JonPSmith,

Yes, I was able to filter it out, just I use autoregister to simplify life, not for complicating and filtering out every records from autoDI. So this should be handled somehow better.

**Comment by JonPSmith** [comment]
Hi @martonx,

I had a quick check and a record has a interface of type `IEquatable<nameof>`, which means that AutoRegisterD will register it. I think I can something to stop that but I'm busy on another library so I won't get to this for a while.

You could try using the  `.IgnoreThisInterface<>` method to ignore `IEquatable<>` but I don't know if that will work because of the `<>` . If you try it, then let me know if it works.

**Comment by JonPSmith** [comment]
Hi @martonx,

I have just released version 2.2.0 of this library which contains a `IgnoreThisGenericInterface` which handles `record`s and their ``IEquatable<- record ->`. You can see the documentation (which I improved) in the [README file](https://github.com/JonPSmith/NetCore.AutoRegisterDi/blob/master/README.md#the-ignorethisgenericinterfacetype-interfacetype-method).

**Comment by martonx** [comment]
Thank you very-very much!
